### ISSUE TITLE
compiler command line option does not work

### ISSUE THREAD

**Issue by garikello3d** [arighi/virtme-ng#121]
If I need to use custom gcc for my kernel to build, I assume that I just use `--compiler=gcc-8` in the command line. Actually the program does not complain. While actually the default `gcc` is used. As a workaround I need to add `HOSTCC=gcc-8 CC=gcc-8` as makefile arguments. 

In short:
This `~/virtme-ng/vng -v --build --compiler=gcc-8` does not use the correct gcc.
This `~/virtme-ng/vng -v --build HOSTCC=gcc-8 CC=gcc-8` uses the correct gcc.

**Comment by arighi** [comment]
Thanks for reporting this! I'm always using the `HOSTCC=... CC=...` way, I find it more intuitive, because it resembles what you usually do with `make`, so I've never noticed that `--compiler` isn't working.

I'll fix this, but I think we should also mark the `--compiler` and `--cross-compile` options as deprecated. Do you see any value to support both syntax's?

**Comment by garikello3d** [comment]
well, I do agree that trying to replicate all env variables with command argument is a dead-end (unless you can terrifically minimize mechanical input of those variable...).

I don't see `--cross-compile` option, in the help message at least, so I don't have an opinion on it...
Besides that, this all put a question against the `--arch` option too, if people are used to providing `ARCH=... CROSS_COMPILE=...` for years.

**Comment by arighi** [comment]
Yeah my bad, I think we used to have `--cross-compile` in the past (or I may be just wrong), now it's just determined by `--arch`. And I agree we should definitely rely on the extra env variables when building the kernel and deprecated all the corresponding options that are trying to mimic these env variables. I'll prepare a new PR (or if you want feel free to submit one). Thanks for bringing up this topic!

**Comment by arighi** [comment]
@garikello3d BTW when you say that --compiler doesn't use the right compiler, you man HOSTCC right? Because CC looks correct to me, it only sets that and not HOSTCC. Is this the same for you?

**Comment by garikello3d** [comment]
oops, rrright, I just double checked and looks like for normal CC it applies the `--compiler` options, but when building host tools - does not.

**Comment by arighi** [comment]
ok thanks, I'll push a fix for that! And will also mark these options as deprecated.

**Comment by arighi** [comment]
@garikello3d feel free to reopen this if you still see compiler-related issues.
