### ISSUE TITLE
The PyPI source tarball for 1.27 doesn't require argparse-manpage

### ISSUE THREAD

**Issue by WOnder93** [arighi/virtme-ng#146]
I don't know why, but the `argparse-manpage` requirement doesn't seem to have propagated into the PyPI release. The `virtme-ng-1.27/virtme_ng.egg-info/requires.txt` file in the source tarball only contains `argcomplete` and `requests`.

**Comment by arighi** [comment]
@WOnder93 good catch! It should be  fixed by #149. Do you think we should cut another version?

**Comment by WOnder93** [comment]
No need to do that for me - I ran into it when packaging for Fedora, but there the argparse-manpage binary is in a separate package from the Python library ( :shrug: ), so the automatic dependency generation doesn't pull it and I had to add an explicit dependency anyway.

BTW, you have a typo in the commit title (".txg").

**Comment by arighi** [comment]
Commit title fixed (thanks again!). I may have to apply other fixes/changes soon, so let's wait a bit before cutting a new version, the missing dependency shouldn't cause much troubles (hopefully).

**Comment by WOnder93** [comment]
Closing, as this is already fixed by #149.
