### ISSUE TITLE
virtme-ng kernel downloader should use native arch without having to pass --arch option

### ISSUE THREAD

**Issue by anisse** [arighi/virtme-ng#173]
On all platforms, the kernel downloader defaults to `amd64` if no architecture is passed on the command line. It should just select the current native architecture instead.

Here is an example, on arm64 machine:

```
> ./vng --run v6.6.50 -v
use v6.6.50/amd64 pre-compiled kernel from https://kernel.ubuntu.com/mainline/v6.6.50/amd64
```
It will then fail to start it, and it's even impossible to specify x86_64 as an architecture in order to start it (but that might be another issue).

**Comment by arighi** [comment]
@anisse can you double check if #176 fixes this? Thanks!

**Comment by anisse** [comment]
I commented on the PR, and I confirmed it worked and fixed this issue.
