### ISSUE TITLE
[Question] is there a way to exec into an existing vng machine?

### ISSUE THREAD

**Issue by Andreagit97** [arighi/virtme-ng#191]
Sometimes it could be useful to access a second shell inside the same virtme-ng machine.  For example, when debugging a verifier issue we could inject some ebpf probes with [`retsnoop`](https://github.com/anakryiko/retsnoop) and watch the result in one shell.  At the same time, in the other terminal, we could run our broken ebpf program to trigger the `retsnoop` output.

I was looking for something similar to `docker --exec`, `kubectl --exec` ... I see that today there is an `--exec` flag but it seems a different thing. Is there a way to create a second shell with existing flags?

BTW this is an amazing tool for debugging verifier failures on random kernels, thank you!

**Comment by arighi** [comment]
Something like this was discussed in #151 using vsock. I usually just run tmux inside the vng session to have multiple sessions. I was also planning to send a PR to start sshd inside the vng instance (as an option), so you can basically ssh into the running vng instance (the code just needs some polishing, I may be able to push something in the next days). It'd be nice to explore also the vsock idea, I haven't played with that very much.
