### ISSUE TITLE
Clarify difference between `virtme-ng` and `virtme-run`

### ISSUE THREAD

**Issue by septatrix** [arighi/virtme-ng#201]
I wanted to add options to my kernel cmdline via `vng --kopt ...` but discovered that the `kopt` flag is only available for `virtme-run`. What is the difference between them? Based on the man page vng can also build the kernel but this does not explain why it accepts different args then virtme-run

**Comment by septatrix** [comment]
After further poking I noticed that vng invokes virtme-run. Would it be possible to just pass unknown parameters along? Or just any was to simply start `/bin/sh` as the init? I had some troubles with starting vng with a custom root fs and this was required to troubleshoot the issue (see #202).

**Comment by matttbe** [comment]
Hello,

> I wanted to add options to my kernel cmdline via `vng --kopt ...` but discovered that the `kopt` flag is only available for `virtme-run`.

Indeed, but can you not use the corresponding `vng --append` (or `-a`) option?

> What is the difference between them?

In the original `virtme` (without `-ng`), there were different commands to generate the kernel config, to create the `initramfs`, and to launch a VM. In this new version (`virtme-ng`), a new command (`vng`) has been added as the main one: to build everything and run the VM. Users should use it, but advanced users can still call the individual ones when needed. As you mentioned, `vng` invokes `virtme-run` when needed.

**Comment by septatrix** [comment]
> Hello,
> 
> > I wanted to add options to my kernel cmdline via `vng --kopt ...` but discovered that the `kopt` flag is only available for `virtme-run`.
> 
> Indeed, but can you not use the corresponding `vng --append` (or `-a`) option?

Not sure. Admittedly I just wrapped `os.execv` in the end to replace the `init=` part of the invocation of qemu. It might have worked but I am not sure of the order in which the automatically generated init and the parts added through `--append` are added (and which order would be required here - not sure if the kernel uses the first or last occurence)

> > What is the difference between them?
> 
> In the original `virtme` (without `-ng`), there were different commands to generate the kernel config, to create the `initramfs`, and to launch a VM. In this new version (`virtme-ng`), a new command (`vng`) has been added as the main one: to build everything and run the VM. Users should use it, but advanced users can still call the individual ones when needed. As you mentioned, `vng` invokes `virtme-run` when needed.

Ah that clears things up. I think it would be most intuitive if `vng` accepted all flags from the subcommands and just passes them through if it does not require them itself but I can also see how that might require a decent chunk of refactoring and leave us with a lot of flags we need to keep for compatibility for a while

**Comment by matttbe** [comment]
> > Hello,
> > > I wanted to add options to my kernel cmdline via `vng --kopt ...` but discovered that the `kopt` flag is only available for `virtme-run`.
> > 
> > 
> > Indeed, but can you not use the corresponding `vng --append` (or `-a`) option?
> 
> Not sure. Admittedly I just wrapped `os.execv` in the end to replace the `init=` part of the invocation of qemu. It might have worked but I am not sure of the order in which the automatically generated init and the parts added through `--append` are added (and which order would be required here - not sure if the kernel uses the first or last occurence)

I guess '--append' should add kernel options at the end, and the last occurrence should count. But best to test.

> > > What is the difference between them?
> > 
> > 
> > In the original `virtme` (without `-ng`), there were different commands to generate the kernel config, to create the `initramfs`, and to launch a VM. In this new version (`virtme-ng`), a new command (`vng`) has been added as the main one: to build everything and run the VM. Users should use it, but advanced users can still call the individual ones when needed. As you mentioned, `vng` invokes `virtme-run` when needed.
> 
> Ah that clears things up. I think it would be most intuitive if `vng` accepted all flags from the subcommands and just passes them through if it does not require them itself but I can also see how that might require a decent chunk of refactoring and leave us with a lot of flags we need to keep for compatibility for a while

Indeed, plus some options have been clarified, some might be used in multiple commands, and it is still good to have a good `--help` menu than telling the user to check the option from the other commands :)

Should we close this ticket if it is clearer now?
