### ISSUE TITLE
Clarify how to boot host's running kernel

### ISSUE THREAD

**Issue by zevweiss** [arighi/virtme-ng#32]
Commit d18d080b0b77f1e6866bf82b8b486a4a7eadcf18 changed the behavior of `vng -r` to try to boot a kernel built from the current working directory instead of the host's running kernel, but didn't update the `--run` flag's `--help` text, which still describes the old behavior.  I use the old behavior heavily, and it's not obvious to me how to achieve that with the current state of the code -- it would be great if the help text (and perhaps README?) could be updated to show how to do that (ideally via some comparably simple flag).

**Comment by SPYFF** [comment]
Hi! Same here, I mostly use the old behavior. It would be convenient to have a flag for that, but what you can do is use `vng -r $(uname -r)`. I agree, its more typing.

**Comment by arighi** [comment]
Yeah, I wasn't really convinced about this behavior change, the more I think about this the more I think we should revert it.

I think a good compromise to make both behaviors quick and efficient could be the following:
 - `vng` without any argument: use the kernel from `./`
 - `vng -r`: use the same kernel installed in the host

In this way both behaviors are easily accessible without too much typing involved and we won't break any old usage.

What do you think?

**Comment by zevweiss** [comment]
> It would be convenient to have a flag for that, but what you can do is use vng -r $(uname -r). I agree, its more typing.

Ah, of course -- despite staring right at it numerous times, somehow the "...or an installed kernel version" part of the help text didn't register, thanks.

> What do you think?

Personally, running another instance of the host's running kernel is what I do most often, so making `vng -r $(uname -r)` slightly easier would be welcome, but it's not terrible as-is -- I'm basically okay either way.

**Comment by arighi** [comment]
Alright, with bf7fad8 the old `vng -r` behavior has been restored and my most common use case (run recompiled kernels from current working directory via `vng`) the behavior is also the same.

I've also updated the documentation accordingly. Closing this issue for now.

**Comment by SPYFF** [comment]
Thanks for the change, after all it makes your usecase more convenient too, it's a win-win!
