### ISSUE TITLE
return value of executed command is not returned back to host

### ISSUE THREAD

**Issue by itaihandler** [arighi/virtme-ng#48]
The return value of the command executed inside the kernel is not returned back to the host.

For example:
```
$ vng -- false
$ echo $?
0
```
In the above case, I would expect vng to return 1.

Another example would be to run `vng -- make` on some kernel module source tree. If make fails, the vng command also returns 0.

It may be possible to workaround this issue by writing a wrapper script that prints the return value of the executed command into a temporary file, but it would be much more convenient had virtme-ng could return it automatically.

**Comment by arighi** [comment]
I've tried to implement this feature in the past, but I've never found a clean way to do that, so I always ended up using the `echo $?` workaround in the guest.

Redirecting stdin/out/err between guests/host is implemented using virtio-serial devices in a nice and clean way, but how would you redirect the return code of a command that runs in a shell session in the guest to the host?

Maybe we could create another "fake" virtio-serial channel, then virtme-init/virtme-ng-init can collect the return code of the command and send it to the host via the fake virtio-serial channel. Then vng on the host should be able to receive the value and return that as the exit code.

In theory it should work, in practice I don't know, I'll do some experiments. :)

**Comment by itaihandler** [comment]
Your suggestion looks pretty good to me.
Some things came to my mind while thinking about it however: 
1. How can the user know if the return value belongs to vng or to the guest command? Maybe we can assign a special return value to vng like in ssh? (255 is reserved for ssh errors).
2. What would happen if the kernel panics while executing the command? I saw that if I pass `panic=-1` to kernel command line and `-no-reboot` to qemu arguments, then the VM shuts down upon panic. vng can then conclude that the return value is not available and return some other reserved value (like 254).
For a more general solution we may want vng to return different return values for restart and shutdown events.

**Comment by arighi** [comment]
> Your suggestion looks pretty good to me. Some things came to my mind while thinking about it however:
> 
>     1. How can the user know if the return value belongs to vng or to the guest command? Maybe we can assign a special return value to vng like in ssh? (255 is reserved for ssh errors).
>

This part should be easy, virtme-init / virtme-ng-init calls the guest command, so when the guest command exits we can easily add the logic to store the return value somewhere and pass it to the host.
 
>     2. What would happen if the kernel panics while executing the command? I saw that if I pass `panic=-1` to kernel command line and `-no-reboot` to qemu arguments, then the VM shuts down upon panic. vng can then conclude that the return value is not available and return some other reserved value (like 254).
>        For a more general solution we may want vng to return different return values for restart and shutdown events.

Maybe `panic=-1` and `-no-reboot` should be the default when running guest scripts directly (running vng in non-interactive mode), I need to think about that. With those options I think vng returns an error code already right?

**Comment by itaihandler** [comment]
Nope. In that case vng returns 0.
You can easily emulate a panic by writing 'c' into /proc/sysrq-trigger

**Comment by itaihandler** [comment]
That looks fine to me.
Your original idea (using a dedicated console for the return value) might be more robust, however: What will happen if the guest command writes by mistake something that happens to be a valid encoded return value string and then cause the guest to crash?

**Comment by arighi** [comment]
> That looks fine to me. Your original idea (using a dedicated console for the return value) might be more robust, however: What will happen if the guest command writes by mistake something that happens to be a valid encoded return value string and then cause the guest to crash?

Yep, I agree. Adding a dedicated console is probably more robust, but it's not trivial and we may go this way later. I'd proceed step by step doing the easiest way first, meaning reusing the stdout console with the encoded errcode, then see if it works and if everything is ok we can improve with the dedicated console.

**Comment by arighi** [comment]
@itaihandler I fiinally found some time to work on this, if you're still here let me know what you think about PR #61
