### ISSUE TITLE
running vng through timeout may leave the terminal in a bad state

### ISSUE THREAD

**Issue by itaihandler** [arighi/virtme-ng#49]
When we run `timeout SECONDS vng -- COMMAND`, if timeout expires the terminal is left in a bad state, i.e. key strokes are not echoed back to the terminal.

Example command that demonstrates the problem:

`timeout 10 vng -- sleep 20`

Notes:
1. By running stty in that bad state we can see that the following settings were disabled after the timeout expired: echo, icanon, brkint. We can also see differences in the min and time settings.
2. It's possible to workaround this issue by entering `reset`.

**Comment by arighi** [comment]
@itaihandler can you test if 654a928 fixes this issue?

**Comment by itaihandler** [comment]
> > @itaihandler can you test if [654a928](https://github.com/arighi/virtme-ng/commit/654a9286e873ce3aca367b3cc5a93b219fecc807) fixes this issue?
> 
> ...or rather check with [05f61b6](https://github.com/arighi/virtme-ng/commit/05f61b6498d6c6882852bd7c468a3a395e3ef442) on top that seems more reliable.
> 
> Thanks!

I tested them both [654a928](https://github.com/arighi/virtme-ng/commit/654a9286e873ce3aca367b3cc5a93b219fecc807) and [05f61b6](https://github.com/arighi/virtme-ng/commit/05f61b6498d6c6882852bd7c468a3a395e3ef442) and they both seem to fix this issue.

**Comment by arighi** [comment]
@itaihandler awesome, thanks for testing and reporting this!
