### ISSUE TITLE
RFI: multiple numa nodes support

### ISSUE THREAD

**Issue by tehcaster** [arighi/virtme-ng#56]
Hi,

I sometimes need to emulate multiple numa memory nodes, and currently it's not easy with virtme-ng, AFAIK. I'll describe my attempts below to hopefully highlight what's needed. Let's say I want to emulate 4GB and 8 cpus total, with 2 nodes 2GB and 4 cpus per node:

```
vng -v -r . -p 8 -m 4G
...
> numactl -H
available: 1 nodes (0)
node 0 cpus: 0 1 2 3 4 5 6 7
node 0 size: 3917 MB
node 0 free: 3806 MB
node distances:
node   0 
  0:  10
```

so we have just 1 node. vng command itself doesn't seem to take a nodes option, so let's try with --qemu_opts
```
> vng -v -r . -p 8 -m 4G --qemu-opts="-numa node,mem=2G -numa node,mem=2G"
...
qemu-system-x86_64: -numa node,mem=2G: numa configuration should use either mem= or memdev=,mixing both is not allowed
```

Oh, --dry-run reveals that it's passing` -m 2G -object memory-backend-memfd,id=mem,size=2G,share=on -numa node,memdev=mem` so let's try adding another node the same way

```
vng -v -r . -p 8 -m 4G --qemu-opts="-object memory-backend-memfd,id=mem1,size=2G,share=on -numa node,memdev=mem1"
...
qemu-system-x86_64: total memory for NUMA nodes (0x180000000) should equal RAM size (0x100000000)
```

Hm, too bad because the 4G is used as both total memory (-m 4G) and also for the first node. I have find no way to avoid that, eventually just edited virtme/commands/run.py where it does qemuargs.extend(["-m" ... hardcoded 4G there so the 2G is only used for the first node.

```
vng -v -r . -p 8 -m 2G --qemu-opts="-object memory-backend-memfd,id=mem1,size=2G,share=on -numa node,memdev=mem1"
...
> numactl -H
available: 1 nodes (0)
node 0 cpus: 0 1 2 3 4 5 6 7
node 0 size: 3917 MB
node 0 free: 3808 MB
node distances:
node   0 
  0:  10 
```

Still one node?  Oh maybe it's the microvm type?

```
vng -v -r . -p 8 -m 2G --disable-microvm --qemu-opts="-object memory-backend-memfd,id=mem1,size=2G,share=on -numa node,memdev=mem1"
> numactl -H
available: 2 nodes (0-1)
node 0 cpus: 0 1 2 3 4 5 6 7
node 0 size: 1972 MB
node 0 free: 1863 MB
node 1 cpus:
node 1 size: 1951 MB
node 1 free: 1940 MB
node distances:
node   0   1 
  0:  10  20 
  1:  20  10 
```

Yep, but the cpus are all on one node, so...

```
vng -v -r . -p 8 -m 2G --disable-microvm --qemu-opts="-object memory-backend-memfd,id=mem1,size=2G,share=on -numa node,memdev=mem1,cpus=4-7"
> numactl -H
available: 2 nodes (0-1)
node 0 cpus: 0 1 2 3
node 0 size: 2014 MB
node 0 free: 1923 MB
node 1 cpus: 4 5 6 7
node 1 size: 1909 MB
node 1 free: 1862 MB
node distances:
node   0   1 
  0:  10  20 
  1:  20  10 
```

Finally what I need, but impossible (AFAIK) to achieve without hacking the code.

So if I could propose a possible solution, if there was a vng parameter that took the number of nodes, created the mem and numa devices and distributed all the total memory and cpus between them uniformly (or near uniformly if not perfectly divisible), and most likely also disabled the microvm to avoid surprises, it would be great.

Maybe there could also be a way to override the total memory without having it assigned all to the first node, to allow a more customized configuration with differently sized nodes or different distribution of cpus to nodes, although I didn't need that at this point.

Thanks for considering!

**Comment by arighi** [comment]
@tehcaster I think you also need to specify `--force-9p`, because virtiofs requires to define a numa node and it would conflict with your custom numa options.

Maybe we should add a `--numa` option that automatically disables virtiofsd...

**Comment by tehcaster** [comment]
Thanks for the tip, yeah --force-9p seems to get rid of the "-object memory-backend-memfd,id=mem,size=2G,share=on -numa node,memdev=mem" part and make it easier to setup individual nodes manually and no need to modify source code.
However if I'd just want X nodes with memory and cpu distributed uniformly among them, virtiofs could be retained if vng took care of the multiple nodes setup.

**Comment by arighi** [comment]
@tehcaster can you post an example qemu command that you would run for such configuration? I'm not very familiar with qemu numa settings, an example would help. :)

Then I would like to add a `--numa` option that can also co-exist with the virtiofsd settings (suggestions for the syntax)?

Thanks!

**Comment by tehcaster** [comment]
What I did with the adjusted source was

`vng -v -r . -p 8 -m 2G --disable-microvm --qemu-opts="-object memory-backend-memfd,id=mem1,size=2G,share=on -numa node,memdev=mem1,cpus=4-7" --dry-run`

which expanded to

`/usr/bin/qemu-system-x86_64 -name virtme-ng -m 4G -chardev socket,id=charvirtfs5,path=/tmp/virtmek95zam19 -device vhost-user-fs-pci,chardev=charvirtfs5,tag=ROOTFS -object memory-backend-memfd,id=mem,size=2G,share=on -numa node,memdev=mem -machine accel=kvm:tcg -device i6300esb,id=watchdog0 -cpu host -parallel none -net none -echr 1 -serial none -chardev stdio,id=console,signal=off,mux=on -serial chardev:console -mon chardev=console -vga none -display none -smp 8 -kernel ./arch/x86/boot/bzImage -append 'virtme_hostname=virtme-ng virtme_link_mods=/home/vbabka/wrk/linux/.virtme_mods/lib/modules/0.0.0 virtme_rw_overlay0=/etc virtme_rw_overlay1=/home virtme_rw_overlay2=/opt virtme_rw_overlay3=/srv virtme_rw_overlay4=/usr virtme_rw_overlay5=/var earlyprintk=serial,ttyS0,115200 console=ttyS0 psmouse.proto=exps "virtme_stty_con=rows 66 cols 253 iutf8" TERM=xterm-256color virtme_chdir=home/vbabka/wrk/linux virtme_user=vbabka rootfstype=virtiofs root=ROOTFS raid=noautodetect ro init=/usr/lib/python3.11/site-packages/virtme/guest/virtme-init' -object memory-backend-memfd,id=mem1,size=2G,share=on -numa node,memdev=mem1,cpus=4-7`

So you could add option --numa_nodes=X where we would invoke:

`vng -v -r . -p 8 -m 4G --numa_nodes=2`

and vng would derive the qemu options:

`--disable-microvm` implied automatically because otherwise the numa configuration is not visible to the guest kernel
`-m 4G` for qemu as we gave vng -m 4G

`-object memory-backend-memfd,id=mem,size=2G,share=on -numa node,memdev=mem` first node for the virtiofs support as usual, but size calculated as 4G divided by 2

`-object memory-backend-memfd,id=mem1,size=2G,share=on -numa node,memdev=mem1,cpus=4-7` - second noded added becauase of --numa_nodes=2, size again derived from the total memory size, cpus=4-7 added to distribute the 8 cpus among the 2 nodes

and analogically for 4 nodes etc...

**Comment by arighi** [comment]
Perfect, this is super helpful! I'll start working on this, thanks!

**Comment by arighi** [comment]
@tehcaster let me know what you think about #57, thanks.

**Comment by tehcaster** [comment]
Thanks! I was now able to achieve what I needed by `vng -r . -m 4G  -p 8 --numa 2G --numa 2G,cpus=4-7`
Maybe the help text could be more obvious?

```
  --numa MEM[,cpus=FIRST_CPU1[-LAST_CPU1]][,cpus=FIRST_CPU2[-LAST_CPU2]]...
                        Create NUMA nodes in the guest (this implicitly disables the microvm architecture)
```

It should perhaps say that it doesn't create NUMA nodes but a numa node, and to create more of them, specify multiple --numa parameters.
Also if I don't match -m 4G to be exact sum of --numa 2G --numa 2G, qemu complaints, e.g.
`qemu-system-x86_64: total memory for NUMA nodes (0x100000000) should equal RAM size (0x40000000)`
The help text could mention that. Or maybe if no -m is passed explicitly, vng could calculate the correct sum automatically?

Thanks!

**Comment by arighi** [comment]
Pushed 4381750d07c34653370b5c929c36b931e1f72b53 to improve the help and added an example to README.md.

About automatically adjusting / checking if the total memory size matches the one specified with `-m` I'd prefer to just mention it in the help and then rely on the underlying qemu logic (let's say in the future qemu relaxes this constraint, I'd like to be able to support it right away). Thanks for all the suggestions!
