### ISSUE TITLE
a -q to undo a -v thats in a shell wrapper ?

### ISSUE THREAD

**Issue by jimc** [arighi/virtme-ng#58]
hi Andrea,

I love this project !
being lazy, Ive got a few shell-fns wapping vng

function vrun__ () {
    vng --verbose --name $GDESC \
	--user root --cwd ../.. \
	-a dynamic_debug.verbose=2 \
	$*
}
alias vrun_1="vrun__ -p 1"
alias vrun_="vrun__ -p 4 "
alias vrun_3="vrun_ -a dynamic_debug.verbose=3"
alias vrun_9="vrun_ --force-9p"

alias vrun_e="vrun_ -e $*"
alias vrun_t="vrun_3 -e tools/testing/selftests/dynamic_debug/dyndbg_selftest.sh"

alias vrun_d="vrun_ -a nokaslr -o=-S -o=-s "
alias vrun_d9="vrun_d --force-9p"

function vrun_a () {
    vrun__ \
	-a drm.debug=0x100 \
	-a i915.dyndbg=class,DRM_UT_CORE,+pfmlt_%class,DRM_UT_KMS,+pfml_%class,DRM_UT_ATOMIC,+pfm \
	$*
}

At the root of it is that --verbose.
It would be convenient to have a -q to undo it in my wrapper scheme

Id be happy to try to patch it myself, but I know its a 2 minute thing for you :-)

**Comment by arighi** [comment]
I like this idea! Let's see if I can do this in 2min :smile:
