### ISSUE TITLE
sudo fails with virtme-ng-init on openSUSE

### ISSUE THREAD

**Issue by marcosps** [arighi/virtme-ng#75]
Last time I did the tests on openSUSE I forgot to test sudo, sorry about it :(

```sh
mpdesouza@virtme-ng:~/git/linux> sudo ls
sudo: unable to open /var/lib/sudo: Permission denied
sudo: /var/lib/sudo/ts: Permission denied

We trust you have received the usual lecture from the local System
Administrator. It usually boils down to these three things:

    #1) Respect the privacy of others.
    #2) Think before you type.
    #3) With great power comes great responsibility.

For security reasons, the password you type will not be visible.

[sudo] password for root: 
sudo: a password is required
```

The permission denied is something that doesn't happen when --no-virtme-ng-init is passed. Have you seen this before?

**Comment by arighi** [comment]
I haven't seen this before, but it seems to be related to some restrictive permissions in `/var/lib/sudo`. We may have to `mount --bind /var/lib/sudo` somewhere else from virtme-ng-init / virtme-init. But it doesn't explain why it's not failing with `--no-virtme-ng-init`... I'll do some tests later today.

**Comment by marcosps** [comment]
Thanks a lot!

**Comment by spikeh** [comment]
I get the same problem on Fedora:

```
$ sudo                                                                                                                                                                                ✘ 1
zsh: permission denied: sudo
```

Latest net-next branch, `vng --kconfig` then `vng -v --disable-microvm`.

I'm running Fedora 39.

Let me know if you need any more info.

**Comment by arighi** [comment]
@spikeh I think I've been able to reproduce the same issue in CachyOS where `sudo` is trying to increase the max limit of open files to a number greater than `/proc/sys/fs/nr_open`, hence hitting the permission denied.

If that's the case we may need to increase the default `/proc/sys/fs/nr_open` in the vng guest (maybe by copying the one from the host). Can you confirm that you're hitting the same issue? For example, if you `echo N > /proc/sys/fs/nr_open` in the guest before running sudo you shouldn't see the permission denied.

However, this is a separate issue from the one that @marcosps found. I'll prepare a fix also for this one.

**Comment by arighi** [comment]
BTW @marcosps what is the best way to request adding `python311-setuptools` and `python311-argcomplete` as dependencies for the package `virtme` in openSUSE? Otherwise the stock vng fails to run after installing it.

**Comment by arighi** [comment]
Alright, #77 should fix all these issues now. Just tested both on the latest openSUSE and CachyOS and everything seems to work fine.

**Comment by marcosps** [comment]
> BTW @marcosps what is the best way to request adding `python311-setuptools` and `python311-argcomplete` as dependencies for the package `virtme` in openSUSE? Otherwise the stock vng fails to run after installing it.

I can do that, let me check.

**Comment by marcosps** [comment]
> Alright, #77 should fix all these issues now. Just tested both on the latest openSUSE and CachyOS and everything seems to work fine.

So I tested your propagate-nr-open branch and it fixed my issue! Thanks a lot!

**Comment by marcosps** [comment]
> > BTW @marcosps what is the best way to request adding `python311-setuptools` and `python311-argcomplete` as dependencies for the package `virtme` in openSUSE? Otherwise the stock vng fails to run after installing it.
> 
> I can do that, let me check.

Done: https://build.opensuse.org/request/show/1149396

Let's wait for it to be merged now. It can take some time until it reaches Tumbleweed :)

**Comment by arighi** [comment]
> > > BTW @marcosps what is the best way to request adding `python311-setuptools` and `python311-argcomplete` as dependencies for the package `virtme` in openSUSE? Otherwise the stock vng fails to run after installing it.
> > 
> > 
> > I can do that, let me check.
> 
> Done: https://build.opensuse.org/request/show/1149396
> 
> Let's wait for it to be merged now. It can take some time until it reaches Tumbleweed :)

Awesome, thanks!
