### ISSUE TITLE
`virt -r` just hangs and manually running qemu-systemd-x86_64 gives `virtme_rw_overlay0=/etc: Could not open 'virtme_rw_overlay0=/etc': No such file or directory`

### ISSUE THREAD

**Issue by paulmenzel** [arighi/virtme-ng#78]
Thank you for this tool.

On our custom distribution MarIuX64, I built virtme-ng from

    $ git log --oneline --no-decorate -1
    bdff482 Merge pull request #74 from WOnder93/fix-setup
    $ pip install .

Building the Linux kernel from current Linux branch *master* with `virt -b`, I try to run it, but it hangs:

    $ vng --build --config /boot/config-6.6.12.mx64.461
    $ vng -r arch/x86/boot/vmlinux.bin

Running the command from the `ps` output directly results in:

    $ qemu-system-x86_64 --version
    QEMU emulator version 7.2.0
    Copyright (c) 2003-2022 Fabrice Bellard and the QEMU Project developers
    $ qemu-system-x86_64 -name virtme-ng -m 1G -fsdev local,id=virtfs5,path=/,security_model=none,readonly=on,multidevs=remap -device virtio-9p-pci,fsdev=virtfs5,mount_tag=/dev/root -machine accel=kvm:tcg -device i6300esb,id=watchdog0 -cpu host -parallel none -net none -echr 1 -serial none -chardev stdio,id=console,signal=off,mux=on -serial chardev:console -mon chardev=console -vga none -display none -smp 128 -kernel arch/x86/boot/vmlinux.bin -append virtme_hostname=virtme-ng virtme_rw_overlay0=/etc virtme_rw_overlay1=/lib virtme_rw_overlay2=/home virtme_rw_overlay3=/opt virtme_rw_overlay4=/srv virtme_rw_overlay5=/usr virtme_rw_overlay6=/var virtme_console=ttyS0 psmouse.proto=exps "virtme_stty_con=rows 45 cols 176 iutf8" TERM=screen virtme_chdir=dev/shm/linux virtme_user=pmenzel rootfstype=9p rootflags=version=9p2000.L,trans=virtio,access=any raid=noautodetect ro quiet loglevel=0 init=/home/pmenzel/.local/lib/python3.11/site-packages/virtme/guest/virtme-init
    qemu-system-x86_64: virtme_rw_overlay0=/etc: Could not open 'virtme_rw_overlay0=/etc': No such file or directory

How do I create these overlays?

**Comment by arighi** [comment]
I think you are missing some quotes/double quotes in your qemu-system-x86_64 command. Try running `vng -vr arch/x86/boot/vmlinux.bin`, the option `-v` should tell you a bit more, so we can better understand where/why it gets stuck.

**Comment by paulmenzel** [comment]
Thank you for responding so quickly. Unfortunately, `--verbose` also does not give more information.

strace gives:

```
newfstatat(AT_FDCWD, "/home/pmenzel/.config/virtme-ng/virtme-ng.conf", 0x7ffe52bbb9b0, 0) = -1 ENOENT (No such file or directory)
newfstatat(AT_FDCWD, "/home/pmenzel/.virtme-ng.conf", 0x7ffe52bbb9b0, 0) = -1 ENOENT (No such file or directory)
newfstatat(AT_FDCWD, "/etc/virtme-ng.conf", 0x7ffe52bbb9b0, 0) = -1 ENOENT (No such file or directory)
openat(AT_FDCWD, "/sys/devices/system/cpu/online", O_RDONLY|O_CLOEXEC) = 3
read(3, "0-127\n", 1024)                = 6
close(3)                                = 0
pipe2([3, 4], O_CLOEXEC)                = 0
rt_sigprocmask(SIG_BLOCK, ~[RTMIN RT_1], [], 8) = 0
vfork()                                 = 16161
rt_sigprocmask(SIG_SETMASK, [], NULL, 8) = 0
close(4)                                = 0
read(3, "", 50000)                      = 0
close(3)                                = 0
wait4(16161,
```

Adding single quotes around the `-append` argument, I got another error:

```
qemu-system-x86_64 -name virtme-ng -m 1G -fsdev local,id=virtfs5,path=/,security_model=none,readonly=on,multidevs=remap -device virtio-9p-pci,fsdev=virtfs5,mount_tag=/dev/root -machine accel=kvm:tcg -device i6300esb,id=watchdog0 -cpu host -parallel none -net none -echr 1 -serial none -chardev file,path=/proc/self/fd/2,id=dmesg -device virtio-serial-pci -device virtconsole,chardev=dmesg -chardev stdio,id=console,signal=off,mux=on -serial chardev:console -mon chardev=console -vga none -display none -smp 128 -kernel arch/x86/boot/vmlinux.bin -append 'virtme_hostname=virtme-ng virtme_rw_overlay0=/etc virtme_rw_overlay1=/lib virtme_rw_overlay2=/home virtme_rw_overlay3=/opt virtme_rw_overlay4=/srv virtme_rw_overlay5=/usr virtme_rw_overlay6=/var console=hvc0 earlyprintk=serial,ttyS0,115200 virtme_console=ttyS0 psmouse.proto=exps "virtme_stty_con=rows 45 cols 176 iutf8" TERM=screen virtme_chdir=dev/shm/linux virtme_user=pmenzel rootfstype=9p rootflags=version=9p2000.L,trans=virtio,access=any raid=noautodetect ro init=/home/pmenzel/.local/lib/python3.11/site-packages/virtme/guest/virtme-init"'
qemu-system-x86_64: Error loading uncompressed kernel without PVH ELF Note
```

Maybe I need a different Linux kernel config. I test with the default config.

**Comment by paulmenzel** [comment]
> Maybe I need a different Linux kernel config. I test with the default config.

In the git checkout, I did `git clean -dfx && git reset --hard`, and got one more warning, but it still hangs.

    $ vng --verbose -r arch/x86/boot/vmlinux.bin
    warning: failed to retrieve kernel version from: arch/x86/boot/vmlinux.bin (modules may not work)

There it hangs. With strace:

```
$ strace -s 2000 -ff vng --verbose -r arch/x86/boot/vmlinux.bin
[…]
[pid 56937] ioctl(11, KVM_SET_USER_MEMORY_REGION, {slot=2, flags=0, guest_phys_addr=0xc3000, memory_size=151552, userspace_addr=0x7f70444c3000}) = 0
[pid 56937] ioctl(11, KVM_SET_USER_MEMORY_REGION, {slot=3, flags=0, guest_phys_addr=0xe8000, memory_size=32768, userspace_addr=0x7f70444e8000}) = 0
[pid 56937] ioctl(11, KVM_SET_USER_MEMORY_REGION, {slot=65537, flags=0, guest_phys_addr=0xc3000, memory_size=0, userspace_addr=0x7f70444c3000}) = 0
[pid 56937] ioctl(11, KVM_SET_USER_MEMORY_REGION, {slot=65538, flags=0, guest_phys_addr=0xd0000, memory_size=0, userspace_addr=0x7f70444d0000}) = 0
[pid 56937] ioctl(11, KVM_SET_USER_MEMORY_REGION, {slot=65537, flags=0, guest_phys_addr=0xc3000, memory_size=151552, userspace_addr=0x7f70444c3000}) = 0
[pid 56937] ioctl(11, KVM_SET_USER_MEMORY_REGION, {slot=65538, flags=0, guest_phys_addr=0xe8000, memory_size=32768, userspace_addr=0x7f70444e8000}) = 0
[pid 56937] ioctl(12, KVM_RUN, 0)       = 0
[pid 56937] ioctl(12, KVM_RUN, 0)       = 0
[pid 56937] ioctl(12, KVM_RUN, 0)       = 0
[pid 56937] ioctl(12, KVM_RUN, 0)       = 0
[pid 56937] ioctl(12, KVM_RUN, 0)       = 0
[pid 56937] ioctl(12, KVM_RUN, 0)       = 0
[pid 56937] ioctl(12, KVM_RUN, 0)       = 0
[pid 56937] ioctl(12, KVM_RUN, 0)       = 0
[pid 56937] ioctl(12, KVM_RUN, 0)       = 0
[pid 56937] ioctl(12, KVM_RUN, 0)       = 0
[pid 56937] ioctl(12, KVM_RUN, 0)       = 0
[pid 56937] ioctl(12, KVM_RUN, 0)       = 0
[pid 56937] ioctl(12, KVM_RUN, 0)       = 0
[pid 56937] getrandom("\x55\x0a\x17\xbd\x95\x1a\x23\xea\xf8\xb8\x68\x30\x2f\x45\x19\xb5\x10\x96\x6c\xd4\x59\x09\xe4\xc1\xaf\x52\x13\xa6\x0e\xaa\x09\x39\x03\x21\x3b\xed\xf5\x7f\x9d\x3f\xab\x82\x85\xfd\x3f\xc0\x6f\x06\xc5\xe1\xd2\xf0\x6d\xac\x13\x97\x00\xe0\x91\xdf\xe7\x52\x31\x47", 64, 0) = 64
[pid 56937] ioctl(12, KVM_RUN, 0)       = 0
[pid 56937] ioctl(12, KVM_RUN, 0)       = 0
[pid 56937] ioctl(12, KVM_RUN <unfinished ...>
[pid 56934] <... clock_nanosleep resumed>0x7f70851fd070) = 0
[pid 56934] clock_nanosleep(CLOCK_REALTIME, 0, {tv_sec=0, tv_nsec=10000000}, 0x7f70851fd070) = 0
[pid 56934] clock_nanosleep(CLOCK_REALTIME, 0, {tv_sec=0, tv_nsec=10000000}, 0x7f70851fd070) = 0
[pid 56934] clock_nanosleep(CLOCK_REALTIME, 0, {tv_sec=0, tv_nsec=10000000}, 0x7f70851fd070) = 0
[pid 56934] clock_nanosleep(CLOCK_REALTIME, 0, {tv_sec=0, tv_nsec=10000000},  <unfinished ...>
[pid 56933] <... ppoll resumed>)        = 0 (Timeout)
[pid 56933] ppoll([{fd=0, events=POLLIN}, {fd=4, events=POLLIN}, {fd=5, events=POLLIN}, {fd=7, events=POLLIN}, {fd=8, events=POLLIN}], 5, {tv_sec=0, tv_nsec=0}, NULL, 8) = 0 (Timeout)
[pid 56933] ppoll([{fd=0, events=POLLIN}, {fd=4, events=POLLIN}, {fd=5, events=POLLIN}, {fd=7, events=POLLIN}, {fd=8, events=POLLIN}], 5, {tv_sec=36430, tv_nsec=999343000}, NULL, 8 <unfinished ...>
[pid 56934] <... clock_nanosleep resumed>0x7f70851fd070) = 0
[pid 56934] clock_nanosleep(CLOCK_REALTIME, 0, {tv_sec=0, tv_nsec=10000000}, 0x7f70851fd070) = 0
[pid 56934] futex(0x562462cf2448, FUTEX_WAIT, 4294967295, NULL
```

**Comment by paulmenzel** [comment]
Oh, stupid me. It looks like, `arch/x86/boot/vmlinux.bin` is not actually the bootable(?) Linux kernel file:

    $ file arch/x86/boot/vmlinux.bin
    arch/x86/boot/vmlinux.bin: data

Using `vmlinux` is better:

    $ file vmlinux
    vmlinux: ELF 64-bit LSB executable, x86-64, version 1 (SYSV), statically linked, BuildID[sha1]=7ad5007e73ac27a98a600bf8945c154674faed2e, with debug_info, not stripped
    $ vng --verbose -r vmlinux
    dpkg is not available, unable to uncompress kernel deb
    $ qemu-system-x86_64 -m 1G -kernel vmlinux -append "earlyprintk=serial console=ttyS0" -nographic
    qemu-system-x86_64: Error loading uncompressed kernel without PVH ELF Note

**Comment by arighi** [comment]
@paulmenzel yep, `vng -r` is expecting one of the following:
 - nothing (in this case it'll try to boot the same kernel running on the host)
 - a kernel binary (like `./arch/x86/boot/bzImage`)
 - a directory (where it'll try to find a valid kernel binary file)
 - an upstream version, for example `vng -r v6.6.17` (in this case vng will download a precompiled upstream kernel from the Ubuntu mainline repository)

The last one is really useful if you need to do a bisect quickly.

**Comment by paulmenzel** [comment]
Thank you for also updating this issue. I just wanted to add the valuable information from issue https://github.com/arighi/virtme-ng/issues/78 here too.

`arch/x86/boot/vmlinux.bin` is the wrong file, and `vmlinux` too. `arch/x86/boot/bzImage` is the one to use, and `vng -r .` in the Linux kernel source directory is going to find it itself.

Thank you again.

**Comment by arighi** [comment]
Correct. Thanks for reporting this, it was a good opportunity to improve the logic to detect the upstream versions.

**Comment by paulmenzel** [comment]
Normally, I just copy paste, what Linux outputs, and now I saw, that with `--verbose` the build process outputs the messages:

    $ vng --build --verbose
    #
    # No change to .config
    #
    Configured.  Build with 'make ARCH=x86 -j128'
    […]
    Kernel: arch/x86/boot/bzImage is ready  (#2)
    $

Maybe that last line could be printed, and for people not liking this, a `--quiet` switch could be added.

**Comment by paulmenzel** [comment]
Last comment, with `CONFIG_PVH=y` `vmlinux` can be booted too. (And saves decompression.)
