### ISSUE TITLE
/dev/stdout: Permission denied

### ISSUE THREAD

**Issue by marcosps** [arighi/virtme-ng#8]
When using kc, and trying to run selftests, it returns an error when executing some selftests

```
/home/mpdesouza/git/linux/tools/testing/selftests/kselftest/runner.sh: line 116: /dev/stdout: Permission denied
```

Checking what's going on...

**Comment by arighi** [comment]
I think you need to run this as sudo, also runner.sh is doing weird things with stdout that is conflicting with how we redirect virtme stdout/console to the host.

**Comment by arighi** [comment]
Yep, theoretically we just all virtme. I have changed something in virtme for the stdout redirection (because it was broken when we were using --script-sh), see commit 9f688bb ("virtme-run: properly forward stdin with --script-sh"):

https://github.com/arighi/virtme/commit/9f688bbdfab2f29c21680936ffd70e0118603bfe

Not sure if this one is related to this issue.

**Comment by arighi** [comment]
BTW are you using --exec with virtme when you see this problem?

**Comment by arighi** [comment]
Also keep in mind that with virtme-run you get a console as root by default, kc will also switch to your user inside the guest. Maybe the behavior is different with virtme simply because you are root?

**Comment by marcosps** [comment]
> Also keep in mind that with virtme-run you get a console as root by default, kc will also switch to your user inside the guest. Maybe the behavior is different with virtme simply because you are root?

Yes, if I execute the commands as root using kc it works.

**Comment by marcosps** [comment]
So I believe this is an expected behavior, since when using virtme we are root by default.

**Comment by arighi** [comment]
Yep, it's the expected behavior if you're not root. This means that we didn't introduce any regression, but it'd be nice to understand why it happens, theoretically you should be able to run this commands as regular user without getting that /dev/stdout permission error. I'll investigate a bit...

**Comment by arighi** [comment]
@marcosps finally I was able to figure this out, see commit e8b14ba. Now we can run kselftests normally inside virtme-ng and handle stdout/stderr separately on the host!
