### ISSUE TITLE
man page is missing

### ISSUE THREAD

**Issue by jpirko** [arighi/virtme-ng#89]
$ man vng                                                           
No manual entry for vng

Any decent pkg should have man page. Could it be added for vng please?

**Comment by arighi** [comment]
Definitely, I've been thinking to create a manpage for a while and the content is pretty much already defined in the README.md.

I'll prioritize this task. :)

**Comment by jpirko** [comment]
Yeah, you don't really have this README handy when you install vng as a package on distro :)

**Comment by arighi** [comment]
@jpirko man page added with #118, I'm closing this for now, if you notice any issue let me know. Thanks!
