### ISSUE TITLE
qemu-8.2.2 breaks vng?

### ISSUE THREAD

**Issue by tehcaster** [arighi/virtme-ng#97]
Hi,

my distro (openSUSE tumbleweed) updated to qemu 8.2.2 today and it seems to have broken vng for me.

There seems to be something wrong with the console. Now when vng -v starts, I get

virtme: waiting for virtiofsd to start
virtme: use 'microvm' QEMU architecture

but then instead of the early boot kernel messages I can briefly see a qemu interactive console prompt, but then some later-stage messages from kernel/init start coming and it ends with the machine shutting itself down (I can see no immediate reason why).

It sorta works when I add -g, as in it doesn't shutdown and I see more output on the text console, but then it doesn't accept input.

I've downgraded qemu back to 8.2.1 for now, hope this report helps anyway.

**Comment by SPYFF** [comment]
I can confirm the same on Debian Unstable.

**Comment by arighi** [comment]
Thanks for reporting this! I'm still using qemu 8.2.1 (Ubuntu hasn't moved to the new version yet).

I'll try to look at this over the weekend, I don't really have enough bandwidth right now (we're pretty busy with the new Ubuntu 24.04 release), so if anyone wants to investigate, you're more than welcome. :)

**Comment by ishitatsuyuki** [comment]
https://patchwork.kernel.org/project/qemu-devel/patch/20240122163607.459769-2-peter.maydell@linaro.org/ looks suspicious.

**Comment by ishitatsuyuki** [comment]
console seems to work, if I remove the stray `-serial none` and replace `console=hvc0` with `console=ttyS0` manually in the qemu cmdline.

**Comment by jfernandez** [comment]
There is a kernel panic with 8.2.2. You can see if when you run `vng -v`. I'm on arch and I had to rollback to 8.2.1.

**Comment by tammela** [comment]
Deleting `-serial none` worked for me as well on alpine edge
